package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/_GestionPersonalStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 05:34:41 PM COT
*/

public class _GestionPersonalStub extends org.omg.CORBA.portable.ObjectImpl implements s_gestion_pacientes.sop_corba.GestionPersonal
{

  public void registrarPersonal (s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPersonal", true);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTOHelper.write ($out, objPersonal);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarPersonal (objPersonal, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPersonal

  public boolean consultarPersonal (int id, s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarPersonal", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objPersonal.value = s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarPersonal (id, objPersonal        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarPersonal

  public boolean consulPersonal (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consulPersonal", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consulPersonal (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consulPersonal

  public boolean existevaloracion (int id, String ocupacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("existevaloracion", true);
                $out.write_long (id);
                $out.write_string (ocupacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return existevaloracion (id, ocupacion        );
            } finally {
                _releaseReply ($in);
            }
  } // existevaloracion

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTO consultarPaciente (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarPaciente", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTO $result = s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarPaciente (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarPaciente

  public boolean registrarPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTO objPacientes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPaciente", true);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTOHelper.write ($out, objPacientes);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarPaciente (objPacientes        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPaciente

  public boolean abrirSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.credencialDTO objCredencial)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("abrirSesion", true);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.credencialDTOHelper.write ($out, objCredencial);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return abrirSesion (objCredencial        );
            } finally {
                _releaseReply ($in);
            }
  } // abrirSesion

  public void registrarCallback (s_gestion_pacientes.sop_corba.AdminCllbckint objCllbck)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCallback", true);
                s_gestion_pacientes.sop_corba.AdminCllbckintHelper.write ($out, objCllbck);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarCallback (objCllbck        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCallback

  public boolean valorarPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO objValorarPaciente)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("valorarPaciente", true);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTOHelper.write ($out, objValorarPaciente);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return valorarPaciente (objValorarPaciente        );
            } finally {
                _releaseReply ($in);
            }
  } // valorarPaciente

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO consultarValoracion (String id, String ocupacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarValoracion", true);
                $out.write_string (id);
                $out.write_string (ocupacion);
                $in = _invoke ($out);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO $result = s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarValoracion (id, ocupacion        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarValoracion

  public boolean existenPacientes (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("existenPacientes", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return existenPacientes (id        );
            } finally {
                _releaseReply ($in);
            }
  } // existenPacientes

  public void eliminarCallback (s_gestion_pacientes.sop_corba.AdminCllbckint objAdmin)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarCallback", true);
                s_gestion_pacientes.sop_corba.AdminCllbckintHelper.write ($out, objAdmin);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                eliminarCallback (objAdmin        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarCallback

  public boolean guardarInfoSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO objInfoSesionDTO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guardarInfoSesion", true);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTOHelper.write ($out, objInfoSesionDTO);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guardarInfoSesion (objInfoSesionDTO        );
            } finally {
                _releaseReply ($in);
            }
  } // guardarInfoSesion

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO consultarInfoSesion (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarInfoSesion", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO $result = s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarInfoSesion (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarInfoSesion

  public void validarValoracion (int id, String ocupacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validarValoracion", true);
                $out.write_long (id);
                $out.write_string (ocupacion);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                validarValoracion (id, ocupacion        );
            } finally {
                _releaseReply ($in);
            }
  } // validarValoracion

  public int contador (int id, String ocupacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("contador", true);
                $out.write_long (id);
                $out.write_string (ocupacion);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return contador (id, ocupacion        );
            } finally {
                _releaseReply ($in);
            }
  } // contador

  public boolean eliminarList (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarList", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarList (id        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarList

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPersonal:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionPersonalStub
