package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/AdminCllbckint.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* miércoles 9 de marzo de 2022 03:00:58 PM COT
*/

public interface AdminCllbckint extends AdminCllbckintOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminCllbckint
