package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/AdminCllbckintOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 05:34:41 PM COT
*/

public interface AdminCllbckintOperations 
{
  void notificar (String nombreCompleto, int id);
} // interface AdminCllbckintOperations
