package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/AdminCllbckintHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 05:34:41 PM COT
*/

abstract public class AdminCllbckintHelper
{
  private static String  _id = "IDL:sop_corba/AdminCllbckint:1.0";

  public static void insert (org.omg.CORBA.Any a, s_gestion_pacientes.sop_corba.AdminCllbckint that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_gestion_pacientes.sop_corba.AdminCllbckint extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (s_gestion_pacientes.sop_corba.AdminCllbckintHelper.id (), "AdminCllbckint");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_gestion_pacientes.sop_corba.AdminCllbckint read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdminCllbckintStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_gestion_pacientes.sop_corba.AdminCllbckint value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static s_gestion_pacientes.sop_corba.AdminCllbckint narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_gestion_pacientes.sop_corba.AdminCllbckint)
      return (s_gestion_pacientes.sop_corba.AdminCllbckint)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_gestion_pacientes.sop_corba._AdminCllbckintStub stub = new s_gestion_pacientes.sop_corba._AdminCllbckintStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static s_gestion_pacientes.sop_corba.AdminCllbckint unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof s_gestion_pacientes.sop_corba.AdminCllbckint)
      return (s_gestion_pacientes.sop_corba.AdminCllbckint)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      s_gestion_pacientes.sop_corba._AdminCllbckintStub stub = new s_gestion_pacientes.sop_corba._AdminCllbckintStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
