package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/GestionPersonal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* jueves 17 de febrero de 2022 11:50:25 AM COT
*/

public interface GestionPersonal extends GestionPersonalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPersonal
