package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/GestionPersonal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 12:07:26 PM COT
*/

public interface GestionPersonal extends GestionPersonalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPersonal
