package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/GestionPersonalPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* miércoles 9 de marzo de 2022 03:00:58 PM COT
*/

public class GestionPersonalPOATie extends GestionPersonalPOA
{

  // Constructors

  public GestionPersonalPOATie ( s_gestion_pacientes.sop_corba.GestionPersonalOperations delegate ) {
      this._impl = delegate;
  }
  public GestionPersonalPOATie ( s_gestion_pacientes.sop_corba.GestionPersonalOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_gestion_pacientes.sop_corba.GestionPersonalOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_gestion_pacientes.sop_corba.GestionPersonalOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registrarPersonal (s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res)
  {
    _impl.registrarPersonal(objPersonal, res);
  } // registrarPersonal

  public boolean consultarPersonal (int id, s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal)
  {
    return _impl.consultarPersonal(id, objPersonal);
  } // consultarPersonal

  public boolean consulPersonal (int id)
  {
    return _impl.consulPersonal(id);
  } // consulPersonal

  public boolean existevaloracion (int id, String ocupacion)
  {
    return _impl.existevaloracion(id, ocupacion);
  } // existevaloracion

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTO consultarPaciente (int id)
  {
    return _impl.consultarPaciente(id);
  } // consultarPaciente

  public boolean registrarPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.PacienteDTO objPacientes)
  {
    return _impl.registrarPaciente(objPacientes);
  } // registrarPaciente

  public boolean abrirSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.credencialDTO objCredencial)
  {
    return _impl.abrirSesion(objCredencial);
  } // abrirSesion

  public void registrarCallback (s_gestion_pacientes.sop_corba.AdminCllbckint objCllbck)
  {
    _impl.registrarCallback(objCllbck);
  } // registrarCallback

  public boolean valorarPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO objValorarPaciente)
  {
    return _impl.valorarPaciente(objValorarPaciente);
  } // valorarPaciente

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO consultarValoracion (String id, String ocupacion)
  {
    return _impl.consultarValoracion(id, ocupacion);
  } // consultarValoracion

  public boolean existenPacientes (int id)
  {
    return _impl.existenPacientes(id);
  } // existenPacientes

  public void eliminarCallback (s_gestion_pacientes.sop_corba.AdminCllbckint objAdmin)
  {
    _impl.eliminarCallback(objAdmin);
  } // eliminarCallback

  public boolean guardarInfoSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO objInfoSesionDTO)
  {
    return _impl.guardarInfoSesion(objInfoSesionDTO);
  } // guardarInfoSesion

  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO consultarInfoSesion (int id)
  {
    return _impl.consultarInfoSesion(id);
  } // consultarInfoSesion

  public void validarValoracion (int id, String ocupacion)
  {
    _impl.validarValoracion(id, ocupacion);
  } // validarValoracion

  public int contador (int id, String ocupacion)
  {
    return _impl.contador(id, ocupacion);
  } // contador

  public boolean eliminarList (int id)
  {
    return _impl.eliminarList(id);
  } // eliminarList

  public boolean validarEstadoPaciente (String id)
  {
    return _impl.validarEstadoPaciente(id);
  } // validarEstadoPaciente

  public boolean existenciaspersonal ()
  {
    return _impl.existenciaspersonal();
  } // existenciaspersonal

  private s_gestion_pacientes.sop_corba.GestionPersonalOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionPersonalPOATie
