package s_gestion_pacientes.sop_corba;


/**
* s_gestion_pacientes/sop_corba/GestionPersonalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* jueves 17 de febrero de 2022 11:50:25 AM COT
*/

public interface GestionPersonalOperations 
{
  void registrarPersonal (s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res);
  boolean consultarPersonal (int id, s_gestion_pacientes.sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal);
  boolean abrirSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.credencialDTO objCredencial);
} // interface GestionPersonalOperations
