package s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage;

/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesPackage/InfoSesionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 05:44:45 PM COT
*/

public final class InfoSesionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTO value = null;

  public InfoSesionDTOHolder ()
  {
  }

  public InfoSesionDTOHolder (s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTOHelper.type ();
  }

}
