package s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage;

/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesPackage/notificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* jueves 17 de febrero de 2022 11:50:43 AM COT
*/

public final class notificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTO value = null;

  public notificacionDTOHolder ()
  {
  }

  public notificacionDTOHolder (s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTOHelper.type ();
  }

}
