package sop_corba;


/**
* sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* lunes 7 de marzo de 2022 02:04:46 AM COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
