package s_seguimiento_pacientes.sop_corba;


/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 05:44:45 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion);
  boolean existevaloracion (int id, String ocupacion);
  boolean guardarValoracionPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO objValorarPaciente);
  boolean guardarInfoSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO objInfoSesion);
  s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO consultarInfoSesion (int id);
  s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO consultarValoracion (String id, String ocupacion);
} // interface GestionNotificacionesOperations
