package s_seguimiento_pacientes.sop_corba;

import s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO;


/**
* s_seguimiento_pacientes/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 08:29:35 AM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

} // interface GestionNotificaciones
