package s_seguimiento_pacientes.sop_corba;


/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 08:29:35 AM COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion);
  boolean guardarValoracionPaciente (s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO objValorarPaciente);
  boolean guardarInfoSesion (s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO objInfoSesion);
  s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.InfoSesionDTO consultarInfoSesion (int id);
} // interface GestionNotificacionesOperations
