package s_seguimiento_pacientes.sop_corba;


/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 05:44:45 PM COT
*/

public abstract class GestionNotificacionesPOA extends org.omg.PortableServer.Servant
 implements s_seguimiento_pacientes.sop_corba.GestionNotificacionesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarNotificacion", new java.lang.Integer (0));
    _methods.put ("existevaloracion", new java.lang.Integer (1));
    _methods.put ("guardarValoracionPaciente", new java.lang.Integer (2));
    _methods.put ("guardarInfoSesion", new java.lang.Integer (3));
    _methods.put ("consultarInfoSesion", new java.lang.Integer (4));
    _methods.put ("consultarValoracion", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionNotificaciones/enviarNotificacion
       {
         s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion = s_seguimiento_pacientes.sop_corba.GestionNotificacionesPackage.notificacionDTOHelper.read (in);
         this.enviarNotificacion (objNotificacion);
         out = $rh.createReply();
         break;
       }

       case 1:  // sop_corba/GestionNotificaciones/existevaloracion
       {
         int id = in.read_long ();
         String ocupacion = in.read_string ();
         boolean $result = false;
         $result = this.existevaloracion (id, ocupacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/GestionNotificaciones/guardarValoracionPaciente
       {
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO objValorarPaciente = s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTOHelper.read (in);
         boolean $result = false;
         $result = this.guardarValoracionPaciente (objValorarPaciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // sop_corba/GestionNotificaciones/guardarInfoSesion
       {
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO objInfoSesion = s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTOHelper.read (in);
         boolean $result = false;
         $result = this.guardarInfoSesion (objInfoSesion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // sop_corba/GestionNotificaciones/consultarInfoSesion
       {
         int id = in.read_long ();
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTO $result = null;
         $result = this.consultarInfoSesion (id);
         out = $rh.createReply();
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.InfoSesionDTOHelper.write (out, $result);
         break;
       }

       case 5:  // sop_corba/GestionNotificaciones/consultarValoracion
       {
         String id = in.read_string ();
         String ocupacion = in.read_string ();
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTO $result = null;
         $result = this.consultarValoracion (id, ocupacion);
         out = $rh.createReply();
         s_gestion_pacientes.sop_corba.GestionPersonalPackage.ValorarPacienteDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionNotificaciones:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionNotificaciones _this() 
  {
    return GestionNotificacionesHelper.narrow(
    super._this_object());
  }

  public GestionNotificaciones _this(org.omg.CORBA.ORB orb) 
  {
    return GestionNotificacionesHelper.narrow(
    super._this_object(orb));
  }


} // class GestionNotificacionesPOA
