package s_seguimiento_pacientes.sop_corba;

/**
* s_seguimiento_pacientes/sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gnotificaciones.idl
* martes 8 de marzo de 2022 08:29:35 AM COT
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public s_seguimiento_pacientes.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (s_seguimiento_pacientes.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_seguimiento_pacientes.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_seguimiento_pacientes.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_seguimiento_pacientes.sop_corba.GestionNotificacionesHelper.type ();
  }

}
