module sop_corba{
    interface GestionPersonal{
        struct personalDTO{
            string tipo_id;
            long id;
            string nombreCompleto;
            string ocupacion;
            string usuario;
            string clave;
        };

        struct credencialDTO{
            string usuario;
            string clave;
            long id;
        };

        void registrarPersonal(in personalDTO objPersonal, out boolean res);
        boolean consultarPersonal(in long id, out personalDTO objPersonal);
        boolean abrirSesion(in credencialDTO objCredencial);
    };
};