package s_gestion_pacientes.sop_corba.GestionPersonalPackage;

/**
* s_gestion_pacientes/sop_corba/GestionPersonalPackage/DatosSesionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 12:07:26 PM COT
*/

public final class DatosSesionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_pacientes.sop_corba.GestionPersonalPackage.DatosSesionDTO value = null;

  public DatosSesionDTOHolder ()
  {
  }

  public DatosSesionDTOHolder (s_gestion_pacientes.sop_corba.GestionPersonalPackage.DatosSesionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_pacientes.sop_corba.GestionPersonalPackage.DatosSesionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_pacientes.sop_corba.GestionPersonalPackage.DatosSesionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_pacientes.sop_corba.GestionPersonalPackage.DatosSesionDTOHelper.type ();
  }

}
