package s_gestion_pacientes.sop_corba.GestionPersonalPackage;


/**
* s_gestion_pacientes/sop_corba/GestionPersonalPackage/InfoSesionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpersonal.idl
* martes 8 de marzo de 2022 01:45:56 PM COT
*/

public final class InfoSesionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idPaciente = (int)0;
  public int numFase = (int)0;
  public String fechaSesion = null;
  public int numSesion = (int)0;
  public int presionArterial = (int)0;
  public int frecuenciaInicial = (int)0;
  public int frecuenciaFinal = (int)0;
  public int saturacionOxigeno = (int)0;
  public String estadoPaciente = null;
  public String observaciones = null;

  public InfoSesionDTO ()
  {
  } // ctor

  public InfoSesionDTO (int _idPaciente, int _numFase, String _fechaSesion, int _numSesion, int _presionArterial, int _frecuenciaInicial, int _frecuenciaFinal, int _saturacionOxigeno, String _estadoPaciente, String _observaciones)
  {
    idPaciente = _idPaciente;
    numFase = _numFase;
    fechaSesion = _fechaSesion;
    numSesion = _numSesion;
    presionArterial = _presionArterial;
    frecuenciaInicial = _frecuenciaInicial;
    frecuenciaFinal = _frecuenciaFinal;
    saturacionOxigeno = _saturacionOxigeno;
    estadoPaciente = _estadoPaciente;
    observaciones = _observaciones;
  } // ctor

} // class InfoSesionDTO
